import type { ZenThemeDefinition } from '../types';
import { TELEGRAM_AVATAR_COLORS } from './shared';

/** ChatGPT Day — white canvas, flat assistant prose, light gray user pills. */
export const classicLightTheme: ZenThemeDefinition = {
  id: 'classic-light',
  name: 'Classic Day',
  colorScheme: 'light',
  colors: {
    bgPrimary: '#FFFFFF',
    bgSurface: '#FFFFFF',
    bgElevated: '#F4F4F5',
    textPrimary: '#000000',
    textSecondary: '#6E6E73',
    textTertiary: '#AEAEB2',
    accent: '#007AFF',
    accentSoft: 'rgba(0,122,255,0.12)',
    accentStrong: '#0066D6',
    statusFailed: '#FF3B30',
    statusBlocked: '#FF3B30',
    statusUnknown: '#FF9500',
    statusRunning: '#34C759',
    statusDone: '#AEAEB2',
    zenGreen: '#34C759',
    priorityUrgent: '#FF3B30',
    priorityHigh: '#FF9500',
    priorityMedium: '#FFCC00',
    priorityLow: '#6E6E73',
    border: 'rgba(0,0,0,0.08)',
    borderSubtle: 'rgba(0,0,0,0.05)',
    borderStrong: 'rgba(0,0,0,0.12)',
    surfaceSubtle: 'rgba(0,0,0,0.04)',
    surfacePressed: 'rgba(0,0,0,0.06)',
    surfaceActive: 'rgba(0,122,255,0.12)',
    inputBackground: '#F4F4F5',
    modalBackdrop: 'rgba(0,0,0,0.40)',
    modalSurface: '#FFFFFF',
    modalSurfaceAlt: '#F4F4F5',
    textOnAccent: '#FFFFFF',
    promptGreen: '#34C759',
    promptYellow: '#FF9500',
    warning: '#FF9500',
    dangerText: '#FF3B30',
    disabledText: '#C7C7CC',
    dangerSoft: 'rgba(255,59,48,0.10)',
    warningSoft: 'rgba(255,149,0,0.12)',
    shadowColor: '#1C1C1E',
  },
  chat: {
    layout: 'chatgpt',
    showWallpaper: false,
    showTimestamps: false,
    showDateDividers: false,
    background: '#FFFFFF',
    sentBubble: '#F4F4F4',
    receivedBubble: '#FFFFFF',
    sentText: '#000000',
    receivedText: '#000000',
    sentTimestamp: 'rgba(0,0,0,0.40)',
    receivedTimestamp: 'rgba(0,0,0,0.35)',
    composerBackground: '#F4F4F4',
    composerBorder: 'transparent',
    composerDock: '#FFFFFF',
    link: '#007AFF',
    patternIcon: 'rgba(0,0,0,0.03)',
  },
  surfaces: {
    card: '#FFFFFF',
    cardStrong: '#FFFFFF',
    subtle: 'rgba(0,0,0,0.03)',
    border: 'rgba(0,0,0,0.08)',
    sectionLabel: '#6E6E73',
  },
  avatarColors: TELEGRAM_AVATAR_COLORS,
};