package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/daoleno/zen/daemon/work"
)

type executorFile struct {
	DelegatedExecutor string          `toml:"delegated_executor"`
	Executors         []work.Executor `toml:"executors"`
}

type configWriteRequest struct {
	Path      string
	Delegated string
	Profile   Profile
	Selected  []selectedExecutor
	Now       time.Time
}

type selectedExecutor struct {
	ID       string
	Provider string
	Existing work.Executor
}

type configWriteResult struct {
	Path       string
	BackupPath string
}

func writeExecutorsConfig(req configWriteRequest) (configWriteResult, error) {
	if strings.TrimSpace(req.Path) == "" {
		return configWriteResult{}, fmt.Errorf("executors path required")
	}
	if strings.TrimSpace(req.Delegated) == "" {
		return configWriteResult{}, fmt.Errorf("delegated executor required")
	}
	if req.Now.IsZero() {
		req.Now = time.Now().UTC()
	}

	existingByName := map[string]work.Executor{}
	var existingRaw []byte
	if raw, err := os.ReadFile(req.Path); err == nil {
		existingRaw = raw
		var parsed executorFile
		if unmarshalErr := toml.Unmarshal(raw, &parsed); unmarshalErr == nil {
			for _, executor := range parsed.Executors {
				name := strings.TrimSpace(executor.Name)
				if name == "" {
					continue
				}
				existingByName[name] = executor
			}
		}
	} else if !os.IsNotExist(err) {
		return configWriteResult{}, err
	}

	outByName := map[string]work.Executor{}
	// Preserve unrelated existing file entries.
	for name, executor := range existingByName {
		if req.Profile == ProfileSafe {
			executor.Command = stripBypassFlags(executor.Command)
			if executor.Command == "" {
				executor.Command = name
			}
		}
		outByName[name] = executor
	}
	// Apply selected executors with profile commands (no silent bypass for Safe).
	for _, selected := range req.Selected {
		existing := selected.Existing
		if prev, ok := existingByName[selected.ID]; ok {
			existing = prev
		}
		command, kind := commandForProfile(selected.Provider, selected.ID, existing.Command, req.Profile)
		if req.Profile == ProfileSafe {
			command = stripBypassFlags(command)
			if command == "" {
				command = selected.ID
			}
		}
		entry := work.Executor{
			Name:    selected.ID,
			Command: command,
			Kind:    kind,
			Runtime: existing.Runtime,
		}
		if entry.Kind == "" {
			entry.Kind = existing.Kind
		}
		outByName[selected.ID] = entry
	}

	names := make([]string, 0, len(outByName))
	for name := range outByName {
		names = append(names, name)
	}
	sort.Strings(names)

	file := executorFile{
		DelegatedExecutor: req.Delegated,
		Executors:         make([]work.Executor, 0, len(names)),
	}
	for _, name := range names {
		file.Executors = append(file.Executors, outByName[name])
	}

	body, err := renderExecutorsTOML(file, req.Profile)
	if err != nil {
		return configWriteResult{}, err
	}

	result := configWriteResult{Path: req.Path}
	if err := os.MkdirAll(filepath.Dir(req.Path), 0o700); err != nil {
		return result, err
	}
	if len(existingRaw) > 0 {
		backup := req.Path + ".bak." + req.Now.UTC().Format("20060102T150405Z")
		if err := os.WriteFile(backup, existingRaw, 0o600); err != nil {
			return result, fmt.Errorf("backup executors.toml: %w", err)
		}
		result.BackupPath = backup
	}

	tmp := req.Path + ".tmp." + fmt.Sprintf("%d", req.Now.UnixNano())
	if err := os.WriteFile(tmp, body, 0o600); err != nil {
		return result, err
	}
	if err := os.Rename(tmp, req.Path); err != nil {
		_ = os.Remove(tmp)
		return result, err
	}
	return result, nil
}

func renderExecutorsTOML(file executorFile, profile Profile) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by zen setup. Review before use.\n")
	b.WriteString("# Profile: " + string(profile) + "\n")
	if profile == ProfileAutonomous {
		b.WriteString("# WARNING: Autonomous profile can bypass approvals/sandbox for some executors.\n")
	} else {
		b.WriteString("# Safe/manual profile: no bypass flags were injected by setup.\n")
	}
	b.WriteString("# Restart zen after changing executor definitions or commands.\n")
	b.WriteString("# Delegated selection can be switched live: zen brain set-delegated <id>\n\n")
	b.WriteString("delegated_executor = \"" + escapeTOMLString(file.DelegatedExecutor) + "\"\n\n")
	for _, executor := range file.Executors {
		b.WriteString("[[executors]]\n")
		b.WriteString("name = \"" + escapeTOMLString(executor.Name) + "\"\n")
		b.WriteString("command = \"" + escapeTOMLString(executor.Command) + "\"\n")
		if kind := strings.TrimSpace(executor.Kind); kind != "" {
			b.WriteString("kind = \"" + escapeTOMLString(kind) + "\"\n")
		}
		if runtime := strings.TrimSpace(executor.Runtime); runtime != "" {
			b.WriteString("runtime = \"" + escapeTOMLString(runtime) + "\"\n")
		}
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}

func escapeTOMLString(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
	)
	return replacer.Replace(value)
}
